# Configuraciones del servidor
server:
  port: 9090
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# Configuraciones de spring cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
      - TokenRelay
      routes:
        - id: ms-bill
          uri: lb://ms-bill
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/v2/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      client:
        provider:
          keycloak-e-commerce:
            issuer-uri: http://localhost:8080/realms/sebastian
        registration:
          keycloak-e-commerce:
            client-id: e-commerce-gateway-client
            client-secret: ZG4rc9to0ChKFeCHo81QZsWPODU2XbYf
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak